### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asynts** [asynts/mpack#2]
## ResetReader
- [ ] add a `reset_to(pos: usize)` method that only resets that part
- [ ] if `reset()` is called and an internal error occurs, it might land in the wrong place.

## ResetGuard
- [ ] the `ResetGuard` should only reset to the position when it was created
    - [ ] the guard must save the cursor position
    - [ ] it must change that position when `apply()` is called
